### ISSUE TITLE
Need prefab to build zos flist

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_prefab#32]
Need to access zos (guest) created on zos (host).
Want to make sure if I mount something from host to guest that it is mounted.

**Comment by muhamadazmy** [comment]
Currently we don't have "automated" builder for zos flist. 
There are 2 methods to build a zos flist
## IPXE flist
This one contains ipxe framework with a ipxe script that boots the latest efi build from the hub plus the boot.yaml file. This currently has some issues:
- Download the efi image every time doesn't make use of fs cache because the image is downloaded from the hub.
- No control on which version to boot
- No way (currently) to pass extra boot arguments to image (may be we need to change the embedded script)

## EFI flist
This one contains the full initramfs efi file, plus of course the boot.yaml file. This one is better than the previous approach in few points:
- U control which version of the efi u boot (0-core version, etc...)
- It make uses of the cache because the efi is served over the fs, which means booting other zos machines on the same node will go much faster
- Supporting passing extra arguments, which allow us to do shared cache with the host.

### Downside
- We need to build a new flist for each efi build.

# Conclusion
I am not sure which flist approach is better but we need to unify. Whatever approach we take it MUST support passing extra arguments to the boot cmdline, otherwise we won't be able to have shared cache, or fine tune the zos gues (farmerid, zerotier, etc...)

**Comment by AhmedHanafy725** [comment]
[auto builder flist](https://hub.grid.tf/tf-autobuilder/zero-os-development.flist.md)
